import { footballLayout } from './football-layout.mjs';
// 作用：在合并阶段为各类报告注入统一深色主题，同时保留原始数据与交互。
export function themeReport(html) {
  html = html.replace(/<style id="fc-unified-theme">[\s\S]*?<\/style>/g, '');
  const css = `<style id="fc-unified-theme">
:root{color-scheme:dark;--bg:#101713;--surface:#161e18;--text:#f5f4eb;--text2:#aeb5aa;--text3:#859080;--border:#30392f;--blue:#8fd6bb;--green:#c8f646}
body{background:#101713!important;color:#f5f4eb!important;font:16px/1.7 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif!important;margin:0!important}
.container{max-width:none!important;padding:8px 0 30px!important}.header{background:none!important;border:0!important;box-shadow:none!important;text-align:left!important;padding:10px 0 24px!important;margin:0!important;position:static!important}.header h1{font-size:28px!important;text-shadow:none!important;color:#f5f4eb!important}.header .meta{justify-content:flex-start!important}.header .subtitle,.header .update-time{color:#aeb5aa!important;text-shadow:none!important}.footer{color:#859080!important;background:none!important}
.standings-section,.news-section,.tweet-card,.news-card,.empty-notice{background:#161e18!important;border:1px solid #30392f!important;border-radius:8px!important;box-shadow:none!important}.standings-section{margin-bottom:24px!important}.standings-header,.news-header,.card-top,.card-footer,.tweet-footer,.news-filter-tabs{border-color:#30392f!important}.standings-header,.news-header{padding:18px!important;background:none!important}.section-label,.title,.card-title,.author-name{color:#f5f4eb!important}.section-divider{height:20px!important;background:none!important}
.type-tabs,.league-tab,.filter-tab,.news-count,.league-active-indicator{background:#1d271b!important;border-color:#3a4438!important;color:#aeb5aa!important}.type-tab,.league-tab,.filter-tab{font-size:14px!important;padding:8px 14px!important}.type-tab.active,.league-tab.active,.filter-tab.active{background:#c8f646!important;color:#11180b!important;border-color:#c8f646!important}.type-tab{color:#aeb5aa!important}.league-tabs,.news-filter-tabs{gap:8px!important;padding:16px!important}
.table-wrapper{overflow:auto!important}.standings-table{font-size:14px!important;color:#d8d2c4!important;min-width:530px}.standings-table th{background:#1d271b!important;color:#aeb5aa!important;border-color:#30392f!important;padding:12px 8px!important}.standings-table td{border-color:#30392f!important;padding:12px 8px!important}.standings-table td:nth-child(2){color:#f5f4eb!important}.standings-table .highlight td,.standings-table tr:hover td{background:#33201c!important}
.news-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;padding:16px!important;gap:16px!important}.card-body{padding:18px!important}.card-title{font-size:18px!important;line-height:1.55!important}.card-summary{font-size:15px!important;color:#aeb5aa!important;-webkit-line-clamp:6!important}.card-team,.card-source a,.source-link{color:#8fd6bb!important}.card-footer{flex-wrap:wrap!important;gap:8px!important;font-size:12px!important}.card-time,.author-handle,.tweet-time{color:#859080!important}.card-league{font-size:12px!important}.news-card[data-league="toutiao"]{border-top:3px solid #c8f646!important}
.tweets-grid{display:block!important}.tweet-card{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(180px,30%);gap:12px 24px!important;padding:24px!important;margin-bottom:16px!important}.tweet-header,.tweet-body-zh,.tweet-original,.tweet-footer,.tweet-no-image{grid-column:1}.tweet-images{grid-column:2;grid-row:1 / span 4;align-self:start;max-height:380px;overflow:auto}.tweet-images img{max-height:330px!important;object-fit:contain!important}.tweet-body-zh{color:#f5f4eb!important;font-size:16px!important}.tweet-original .orig-text,.tweet-no-image{background:#101713!important;color:#aeb5aa!important}.section-title{border-color:#c8f646!important}.avatar{background:#c8f646!important;color:#11180b!important}a:focus-visible,button:focus-visible{outline:2px solid #e3b341;outline-offset:3px}
@media(max-width:700px){.news-grid{grid-template-columns:1fr!important;padding:8px!important}.tweet-card{display:block!important;padding:16px!important}.tweet-images{margin-top:16px;max-height:none}.standings-header{flex-wrap:wrap;gap:12px}.header h1{font-size:24px!important}}
</style>`;
  return footballLayout(html.replace('</head>', css+'</head>'));
}
