import { footballLayout } from './football-layout.mjs';
// 作用：在合并阶段为各类报告注入统一深色主题，同时保留原始数据与交互。
export function themeReport(html) {
  html = html.replace(/<style id="fc-unified-theme">[\s\S]*?<\/style>/g, '');
  const css = `<style id="fc-unified-theme">
:root{color-scheme:dark;--bg:#101611;--surface:#151d16;--text:#edf0e9;--text2:#b5c0af;--text3:#a2af9b;--border:#33402e;--blue:#c0fa39;--green:#c0fa39}
body{background:#101611!important;color:#edf0e9!important;font:16px/1.7 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif!important;margin:0!important}
.container{max-width:none!important;padding:8px 0 30px!important}.header{background:none!important;border:0!important;box-shadow:none!important;text-align:left!important;padding:10px 0 24px!important;margin:0!important;position:static!important}.header h1{font-size:28px!important;text-shadow:none!important;color:#edf0e9!important}.header .meta{justify-content:flex-start!important}.header .subtitle,.header .update-time{color:#b5c0af!important;text-shadow:none!important}.footer{color:#a2af9b!important;background:none!important}
.standings-section,.news-section,.tweet-card,.news-card,.empty-notice{background:#151d16!important;border:1px solid #33402e!important;border-radius:8px!important;box-shadow:none!important}.standings-section{margin-bottom:24px!important}.standings-header,.news-header,.card-top,.card-footer,.tweet-footer,.news-filter-tabs{border-color:#33402e!important}.standings-header,.news-header{padding:18px!important;background:none!important}.section-label,.title,.card-title,.author-name{color:#edf0e9!important}.section-divider{height:20px!important;background:none!important}
.type-tabs,.league-tab,.filter-tab,.news-count,.league-active-indicator{background:#1b271a!important;border-color:#3b4a32!important;color:#b5c0af!important}.type-tab,.league-tab,.filter-tab{font-size:14px!important;padding:8px 14px!important}.type-tab.active,.league-tab.active,.filter-tab.active{background:#c0fa39!important;color:#17220b!important;border-color:#c0fa39!important}.type-tab{color:#b5c0af!important}.league-tabs,.news-filter-tabs{gap:8px!important;padding:16px!important}
.table-wrapper{overflow:auto!important}.standings-table{font-size:14px!important;color:#cbd3c5!important;min-width:530px}.standings-table th{background:#1b271a!important;color:#bac6b2!important;border-color:#33402e!important;padding:12px 8px!important}.standings-table td{border-color:#2a3726!important;padding:12px 8px!important}.standings-table td:nth-child(2){color:#edf0e9!important}.standings-table .highlight td,.standings-table tr:hover td{background:#24321c!important}
.news-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;padding:16px!important;gap:16px!important}.card-body{padding:18px!important}.card-title{font-size:18px!important;line-height:1.55!important}.card-summary{font-size:15px!important;color:#b5c0af!important;-webkit-line-clamp:6!important}.card-team,.card-source a,.source-link{color:#c0fa39!important}.card-footer{flex-wrap:wrap!important;gap:8px!important;font-size:12px!important}.card-time,.author-handle,.tweet-time{color:#a2af9b!important}.card-league{font-size:12px!important}.news-card[data-league="toutiao"]{border-top:3px solid #c0fa39!important}
.tweets-grid{display:block!important}.tweet-card{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(180px,30%);gap:12px 24px!important;padding:24px!important;margin-bottom:16px!important}.tweet-header,.tweet-body-zh,.tweet-original,.tweet-footer,.tweet-no-image{grid-column:1}.tweet-images{grid-column:2;grid-row:1 / span 4;align-self:start;max-height:380px;overflow:auto}.tweet-images img{max-height:330px!important;object-fit:contain!important}.tweet-body-zh{color:#edf0e9!important;font-size:16px!important}.tweet-original .orig-text,.tweet-no-image{background:#101611!important;color:#aebba5!important}.section-title{border-color:#c0fa39!important}.avatar{background:#c0fa39!important;color:#17220b!important}a:focus-visible,button:focus-visible{outline:2px solid #c0fa39;outline-offset:3px}
@media(max-width:700px){.news-grid{grid-template-columns:1fr!important;padding:8px!important}.tweet-card{display:block!important;padding:16px!important}.tweet-images{margin-top:16px;max-height:none}.standings-header{flex-wrap:wrap;gap:12px}.header h1{font-size:24px!important}}
</style>`;
  return footballLayout(html.replace('</head>', css+'</head>'));
}
